# Generated by Django 3.1.3 on 2022-05-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201209_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='images/default_user_image.jpg', upload_to='images'),
        ),
    ]
