# Generated by Django 3.1.3 on 2022-05-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
